Altered the parameter from String columnName to int columnIndex
Samyssmile/edux pull request #111
Opened 2023-11-09 16:54 UTC by ANURAGSISODIYAA

fixes#108

The parameter in the getColumnDataOf method within DataProcessor is changed from String columnName to int columnIndex due to identified design shortcomings.

class location : lib/src/main/java/de/edux/data/provider/DataProcessor.java

![image](https://github.com/Samyssmile/edux/assets/122148320/36d3bcbd-c544-4a57-a313-4636506a6d83)

2023-11-09 23:36 UTC, Samyssmile commented
@ANURAGSISODIYAA @acsolle66 
I think this will not work, did you run **DecisionTreeExampleOnPenguinsDatasetNoHead.java** ? This class must run without any exceptions.

This looks wrong.
`  public DataPostProcessor imputation(int columnIndex, ImputationStrategy imputationStrategy) {
    String columnName = getColumnNames()[columnIndex];`

2023-11-09 23:38 UTC, Samyssmile requested changes
Run the main() in 
`DecisionTreeExampleOnPenguinsDatasetNoHead`

set 

`  private static final boolean SKIP_HEAD = false;`

Pls join our discord chat, if you have more questions.

2023-11-12 10:48 UTC, Samyssmile commented
@ANURAGSISODIYAA Do you still work on this?

2023-11-15 05:45 UTC, ANURAGSISODIYAA commented
Hi @Samyssmile,

I wanted to update you that due to ongoing semister exams, I'm currently unable to dedicate time to the project. I appreciate your feedback and guidance. Thank you for your understanding.

Best regards, @ANURAGSISODIYAA

2023-11-15 13:45 UTC, closed without merging